import image1 from "./assets/sample-img-1.jpg";
import image2 from "./assets/sample-img-2.jpg";
import image3 from "./assets/sample-img-3.jpg";
import image4 from "./assets/sample-img-4.jpg";
import image5 from "./assets/sample-img-5.jpg";
import image6 from "./assets/sample-img-6.jpg";

const Userdata = [
  {
    name: "Angela Su",
    url: "angelasu",
    title: "Illustrator",
    website: "AngelaSu.com",
    since: "2022",
    location: "California, USA",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
    language: "English, Hindi",
    links: {
      facebook: "facebook.com",
      instagram: "instagram.com",
      twitter: "twitter.com",
    },
    skills: {
      1: "Digital marketing",
      2: "Illustration",
      3: "Web development",
    },
    education: "B.Sc. - Bs Commerce",
    certification: "Certified In Commerce Industry",
    coverImg: "assets/coverimg/coverImg.jpeg",
    image: [image1, image2, image3, image4, image5, image6],
    products: [
      {
        name: "Angela Su",
        url: "angelasu/1",
        parenturl: "/angelasu",
        heading: "Bigbang",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/2",
        parenturl: "/angelasu",
        heading: "hello",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/3",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/4",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/5",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/6",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/7",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/8",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/9",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/10",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/11",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Angela Su",
        url: "angelasu/12",
        parenturl: "/angelasu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
    ],
  },
  {
    name: "Super Su",
    url: "supersu",
    title: "Illustrator",
    website: "AngelaSu.com",
    since: "2022",
    location: "California, USA",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
    language: "English, Hindi",
    links: {
      facebook: "facebook.com",
      instagram: "instagram.com",
      twitter: "twitter.com",
    },
    skills: {
      1: "Digital marketing",
      2: "Illustration",
      3: "Web development",
    },
    education: "B.Sc. - Bs Commerce",
    certification: "Certified In Commerce Industry",
    coverImg: "assets/coverimg/coverImg.jpeg",
    image: [image1, image2, image3, image4, image5, image6],
    products: [
      {
        name: "Super Su",
        url: "supersu/1",
        parenturl: "/supersu",
        heading: "Bigbang",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/2",
        parenturl: "/supersu",
        heading: "hello",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/3",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/4",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/5",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/6",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "angelasu/7",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/8",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/9",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/10",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/11",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
      {
        name: "Super Su",
        url: "supersu/12",
        parenturl: "/supersu",
        heading: "Bigboss",
        location: "California, USA",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel massa sed dolor pulvinar varius ut at velit.",
        language: "English, Hindi",
        pricing: "200$",
        date: "9 sept 2022",
        image: [image1, image2, image3, image4, image5, image6],
      },
    ],
  },
];

export default Userdata;
